
all:	include frontera lonestar6 stampede2 


include:
	echo "====== Building includes ======"
	cd ../include; make;

#corral: FORCE
#	echo "====== Building Corral ======"
#	cd corral; make;

frontera: FORCE
	echo "====== Building Frontera ======"
	cd frontera; make;

lonestar6: FORCE
	echo "====== Building Lonestar6  ======"
	cd 6lonestar; make; 

#maverick2: FORCE
#	echo "====== Building Maverick2 ======"
#	cd 2mav; make;

#ranch: FORCE
#	echo "====== Building Ranch  ======"
#	cd ranch; make; 

stampede2: FORCE
	echo "====== Building Stampede2 ======"
	cd stampede2; make;

FORCE:	
