MAVERICK2_OBJS	=	\
		notices.md \
		overview.md \
		access.md \
		files.md \
		running.md \
		scripts.md \
		vis.md \
		software.md \
		../../include/maverick2-help.md \
		references.md
		
all:	maverick2

maverick2:	$(MAVERICK2_OBJS)
	cat $(MAVERICK2_OBJS) > maverick2.md
	/bin/mv maverick2.md ..


