SRC =   \
        notices.md \
        intro.md \
        access.md \
		using.md \
        files.md \
        building.md \
        running.md \
		scripts.md \
        monitoring.md \
        vis.md \
        programming.md \
        references.md \
		../../include/stampede2-help.md \
        history.md


stampede2:	$(SRC) 
	cat $(SRC) > stampede2.md
	/bin/mv stampede2.md ..

